// Sandboxed execution of LLM-generated value generators.
//
// During discovery, the LLM may identify dynamic values in API requests
// (timestamps, fingerprints, signatures) that the runtime cannot reproduce
// statically. Rather than hardcoding format primitives, we let the LLM write a
// small JS function that produces the value, and run it in a constrained vm
// context.
//
// SECURITY: Node's built-in `vm` module is NOT a security boundary against
// motivated attackers — escape via constructor chains is a known issue. This is
// acceptable for the current threat model (local tool, strategies generated by
// the user's own LLM session). When skills get published across users, this
// should switch to `isolated-vm` or WASM, with a trust prompt before first
// execution.

import vm from 'vm';
import nodeCrypto from 'crypto';

export type GeneratorEntry = { code: string } | { instruction: string; examples?: string[] };

interface GeneratorResolution {
  resolved: Record<string, string>;
  needsLlm: Record<string, { instruction: string; examples?: string[] }>;
}

// Allowlisted crypto surface — primitives the LLM needs to reproduce
// client-side fingerprints / signatures, nothing more.
const safeCrypto = {
  randomUUID: (): string => nodeCrypto.randomUUID(),
  randomBytes: (n: number): Buffer => nodeCrypto.randomBytes(n),
  createHash: (alg: string) => nodeCrypto.createHash(alg),
  createHmac: (alg: string, key: string | Buffer) => nodeCrypto.createHmac(alg, key),
};

export function runGeneratorCode(code: string, args: Record<string, unknown>): string {
  // CRITICAL: the entire user code must execute INSIDE vm.runInContext, not via
  // a function reference returned from it — Node's vm timeout only fires during
  // the initial run, not on later invocations of returned functions. We inject
  // `crypto` and `args` as globals on the sandbox and wrap the user code in an
  // IIFE so they can use `return`.
  const wrapped = `(function(){ ${code} })()`;

  const sandbox: Record<string, unknown> = {
    Date,
    Math,
    Buffer,
    JSON,
    String,
    Number,
    Array,
    Object,
    parseInt,
    parseFloat,
    encodeURIComponent,
    decodeURIComponent,
    crypto: safeCrypto,
    // Freeze args so generator code cannot mutate caller state.
    args: Object.freeze({ ...args }),
  };

  const ctx = vm.createContext(sandbox);
  // Generator snippets are local strategy code evaluated inside the restricted
  // context above; see the module SECURITY note for the trust boundary.
  // eslint-disable-next-line sonarjs/code-eval -- local strategy generator sandbox
  const result = vm.runInContext(wrapped, ctx, { timeout: 100 }) as unknown;
  if (typeof result !== 'string') {
    throw new Error(`Generator must return a string, got ${typeof result}`);
  }
  return result;
}

export function resolveGenerated(
  generated: Record<string, GeneratorEntry> | undefined,
  overrides: Record<string, string> | undefined,
  args: Record<string, unknown>,
): GeneratorResolution {
  const resolved: Record<string, string> = {};
  const needsLlm: Record<string, { instruction: string; examples?: string[] }> = {};
  if (!generated) return { resolved, needsLlm };

  for (const [k, entry] of Object.entries(generated)) {
    // Caller-provided override always wins (instruction-form retry case).
    const override = overrides?.[k];
    if (override !== undefined) {
      resolved[k] = override;
      continue;
    }
    if ('code' in entry) {
      try {
        resolved[k] = runGeneratorCode(entry.code, args);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        throw new Error(`Generator '${k}' failed: ${msg}`, { cause: err });
      }
    } else {
      needsLlm[k] = { instruction: entry.instruction, examples: entry.examples };
    }
  }
  return { resolved, needsLlm };
}
